### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by simonjduff** [TorrensJoaquin/GERG2008#2]
Hi Joaquin,
There's no licence file in this repository, so I'm not sure whether you're open to this being used by others or if the code is just here for reference. 
Would you mind adding a licence file? The convention is simply to put your licence terms in a file named LICENCE.md in the root of your repository. (I'd love to see it with an [MIT](https://opensource.org/license/mit/) licence, but anything describing permitted use would be helpful)
Thanks!

**Comment by TorrensJoaquin** [comment]
Of course Simon. Sorry, I'm more on the engineer side than on the IT side.
Best Regards.

**Comment by simonjduff** [comment]
Amazing, thanks a lot!
